name: Conditional Job Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: |
          echo "Running Job 1"
          # Uncomment the following line to simulate a failure
          # exit 1

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: Job 1 failed, running Job 2
        run: echo "Job 1 failed. This is Job 2 executing now."

  job3:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Job 1 succeeded, running Job 3
        run: echo "Job 1 succeeded. This is Job 3 executing now."
